sonar.projectKey=banking-platform
sonar.projectName=Banking Platform
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*_test.go,**/*.test.ts,**/*.test.js,**/dist/**,deploy/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.js
sonar.sourceEncoding=UTF-8
